name: Build Blender for Linux and Archive

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build-linux:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up dependencies (Ubuntu 22.04 / Debian 12 compatible)
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          git \
          cmake \
          ninja-build \
          libx11-dev \
          libxi-dev \
          libxcursor-dev \
          libxrandr-dev \
          libxinerama-dev \
          libglew-dev \
          libgl1-mesa-dev \
          libpng-dev \
          libtiff-dev \
          libopenexr-dev \
          libfftw3-dev \
          libopenjpeg-dev \
          libopenal-dev \
          libalut-dev \
          libvorbis-dev \
          libogg-dev \
          libtheora-dev \
          libssl-dev \
          libsdl1.2-dev \
          libfreetype6-dev \
          libtbb-dev \
          libboost-all-dev \
          libjemalloc-dev \
          libgmp-dev \
          libmpfr-dev \
          libpotrace-dev \
          libspnav-dev \
          libsdl2-dev \
          libwayland-dev \
          yasm \
          wget \
          python3 \
          python3-dev \
          python3-pip \
          p7zip-full

    - name: Build Blender
      run: |
        mkdir build_linux
        cd build_linux
        cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release
        ninja

    - name: Prepare archive directory
      run: |
        mkdir -p blender-dist
        cp -r build_linux/* blender-dist/
        # Optionally include other files, e.g., scripts, configs, etc.

    - name: Compress entire build directory with 7z
      run: |
        7z a blender-linux-build.7z ./blender-dist/*

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: blender-linux-build
        path: blender-linux-build.7z
