name: Build Blender on Linux

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout forked repository
      uses: actions/checkout@v4

    - name: Install initial packages
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 git git-lfs p7zip-full

    - name: Install building dependencies
      run: |
        sudo ./build_files/build_environment/install_linux_packages.py

    - name: Download precompiled libraries
      run: |
        make update

    - name: Build Blender
      run: |
        make

    - name: Create 7z archive of build directory
      run: |
        7z a blender-build.7z ./build_linux/bin

    - name: Upload 7z archive
      uses: actions/upload-artifact@v4
      with:
        name: blender-build-7z
        path: ./blender-build.7z
